# Generated by Django 5.0.6 on 2024-05-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
